### ISSUE TITLE
Deployment failed: Error: Status: 403. Message: Node run failed with exit code 2

### ISSUE THREAD

**Issue by dalezak** [einaregilsson/beanstalk-deploy#1]
I'm having troubles getting `beanstalk-deploy` to work inside my GitHub Actions, keep getting `403` error.

```
Run einaregilsson/beanstalk-deploy@v1
  with:
    aws_access_key: ABC123
    aws_secret_key: XYZ789
    application_name: our-beanstalk-app
    environment_name: our-beanstalk-app-env
    region: ca-central-1
    version_label: 8
    deployment_package: deploy.zip
  env:
    CI: true
    AWS_ACCESS_KEY_ID: ABC123
    AWS_SECRET_ACCESS_KEY: XYZ789
Uploading file to bucket elasticbeanstalk-ca-central-1-302080953439
```
```
##[error]Deployment failed: Error: Status: 403. Message: 
##[error]Node run failed with exit code 2
```

I installed the package locally and able to successfully run it from the command line:
```
AWS_ACCESS_KEY_ID=ABC123 AWS_SECRET_ACCESS_KEY=XYZ789 beanstalk-deploy our-beanstalk-app our-beanstalk-app-env 8 ca-central-1 deploy.zip
```

Any ideas why it's working from the command line but not via GitHub Actions?

**Comment by dalezak** [comment]
I noticed the line https://github.com/einaregilsson/beanstalk-deploy/blob/master/aws-api-request.js#L10
```
secretKey = options.secretKey || awsApiRequest.secretKey || process.env.AWS_SECRET_SECRET_KEY
```
Is `AWS_SECRET_SECRET_KEY` a typo?

**Comment by einaregilsson** [comment]
Thanks! That's definitely a typo, I've just fixed it and pushed a @v2 tag. However, that shouldn't have been an issue, because in https://github.com/einaregilsson/beanstalk-deploy/blob/master/beanstalk-deploy.js#L198

```awsApiRequest.secretKey = process.env.INPUT_AWS_SECRET_KEY;```

We set the secret key explicitly to the input secret key, so

```secretKey = options.secretKey || awsApiRequest.secretKey || process.env.AWS_SECRET_SECRET_KEY```

should have used that instead of the typo environment variable. Is there any chance you're putting an empty value in for the secret key in here:
```
 with:
    aws_access_key: ABC123
    aws_secret_key: XYZ789
```

You shouldn't have to put any environment variables like this in:

```
env:
    CI: true
    AWS_ACCESS_KEY_ID: ABC123
    AWS_SECRET_ACCESS_KEY: XYZ789
```

The aws_access_key and aws_secret_key from 
```
 with:
    aws_access_key: ABC123
    aws_secret_key: XYZ789
```

should be enough.

**Comment by dalezak** [comment]
So I originally tried using GitHub secrets, but that wasn't working
```
aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

So thought maybe those keys weren't getting loading, so tried hardcoding them instead.
```
with:
    aws_access_key: ABC123
    aws_secret_key: XYZ789
```

But that wasn't working either so added `env` values hoping if `secretKey` wasn't getting set properly if would fall back to the environment variables.
```
env:
    AWS_ACCESS_KEY_ID: ABC123
    AWS_SECRET_ACCESS_KEY: XYZ789
```

Any insight what could be wrong from the last log message?
```
Uploading file to bucket elasticbeanstalk-ca-central-1-302080953439
```

**Comment by dalezak** [comment]
Note, I checked the S3 bucket and the latest uploaded version was the one from the command line, so it must be failing on uploading to S3 step in the GitHub Action.

**Comment by dalezak** [comment]
_Oh!_ I was using a timestamp like `yyyy-MM-dd'T'HH:mm'Z'` as the version number, when I changed it to just a number, the zip was successfully uploaded to S3! 

So that must be the problem. Any suggestion on how to use a date as the version number?

**Comment by einaregilsson** [comment]
The problem seems to be the semicolons. From the AWS docs:

![Screenshot 2019-11-15 at 14 52 30](https://user-images.githubusercontent.com/557149/68952349-9c3eea80-07b7-11ea-96ab-72c0ff51ee87.png)

I tried URI encoding the key name but was still getting errors. Your best bet is to just replace those : with underscores or dashes, that should be fine.

**Comment by einaregilsson** [comment]
But also, if you need a build number generator, I can recommend another action I made which generates sequential build numbers: https://github.com/einaregilsson/build-number

**Comment by dalezak** [comment]
Thanks again @einaregilsson! The `:` in the timestamp must have been the problem. I'm gonna try a timestamp with the format `YYYY-MM-dd-HH-mm` or `YYYYMMddHHmm` this morning. Hopefully that works because it would be more meaningful of a version number for us. I'll keep you posted 👍

**Comment by dalezak** [comment]
So, it took jumping through lots of hoops, but I was able to generate a timestamp in a S3 safe format like `2019-11-15T17-51-47-861Z` :+1: 

```
name: PROD Lint, Build, Deploy

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    
    - uses: actions/checkout@v1
    - name: Use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Run npm install, lint
      run: |
        npm ci
        npm install
    
    - name: Generate deployment package
      run: zip -r deploy.zip . -x ".git/*" -x ".github/*" -x ".vscode/*"
      
    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time
    
    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'  
            
    - name: Run beanstalk-deploy
      uses: einaregilsson/beanstalk-deploy@v2
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: our-beanstalk-app
        environment_name: our-beanstalk-app-env
        region: ca-central-1
        version_label: "${{ steps.format-time.outputs.replaced }}"
        deployment_package: deploy.zip       
```

Thanks for your help on this. And for your GitHub Action! 🤗
