### ISSUE TITLE
Cannot read property 'DescribeApplicationVersionsResult' of undefined

### ISSUE THREAD

**Issue by hanucito** [einaregilsson/beanstalk-deploy#10]
I have the following error `Cannot read property 'DescribeApplicationVersionsResult' of undefined`.
I checked the code and it seems that it breaks at `beanstalk-deploy.js:243`.

I tried with `aws elasticbeanstalk describe-application-versions --application-name {my-app}` and I have a successful response, so, it seems that the bug is related to `beanstalk-deploy`.

**Comment by einaregilsson** [comment]
Ok, can you post your yaml setup here? Just wondering whether there are some errors in the inputs.

**Comment by mbajur** [comment]
I have the exact same issue, here is my yaml config:

```
name: Deploy master
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Generate deployment package
      run: zip -r deploy.zip .

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v6
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: xxx
        environment_name: yyy
        version_label: ${{ github.ref }}
        region: us-east-1
        deployment_package: deploy.zip
```

**Comment by einaregilsson** [comment]
@mbajur ok, have you tried running it as a script locally to deploy? Does it work there?

**Comment by edmarmb** [comment]
I'm facing the same issue.

```yaml
name: Deploy Staging
on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Install NPM Packages
        run: npm install

      - name: Run the unit tests
        run: npm run test

      - name: Build Source
        run: npm run build

      - name: Generate deployment package
        run: zip deploy.zip dist/*

      - name: Deploy to AWS ELB
        uses: einaregilsson/beanstalk-deploy@v6
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: APP_NAME
          environment_name: ENV_NAME
          version_label: LABEL
          region: us-west-2
          deployment_package: deploy.zip
```

Action Result:
```bash
##[error]Deployment failed: TypeError: Cannot read property 'DescribeApplicationVersionsResult' of undefined
Run einaregilsson/beanstalk-deploy@v6
Beanstalk-Deploy: GitHub Action for deploying to Elastic Beanstalk.
https://github.com/einaregilsson/beanstalk-deploy

##[error]Deployment failed: TypeError: Cannot read property 'DescribeApplicationVersionsResult' of undefined
```

Same behaviour if running it locally

```bash
>   AWS_ACCESS_KEY_ID=access_KEY \  
    AWS_SECRET_ACCESS_KEY=secret_KEY \  
    node beanstalk-deploy.js \
    MyApplicationName \
    MyApplication-Environment \
    12345 \
    us-west-2 \
    deploy.zip

Beanstalk-Deploy: GitHub Action for deploying to Elastic Beanstalk.
https://github.com/einaregilsson/beanstalk-deploy

Deployment failed: TypeError: Cannot read property 'DescribeApplicationVersionsResult' of undefined
```

Any ideas of can be the issue?
