### ISSUE TITLE
Deploy Elastic Beanstack using Assume role

### ISSUE THREAD

**Issue by Purushotham-grip** [einaregilsson/beanstalk-deploy#105]
Hi,

Im using below script to Deploy EB using assume role I'm i doing anything wrong

- name: Deploy to ElasticBeanstalk
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_role_arn: ${{ steps.assume_role.outputs.role_arn }}
          application_name: ${{ github.event.inputs.APPLICATION_NAME }}
          version_label: '${{ steps.extract_branch.outputs.branch }}-${{ steps.format_time.outputs.replaced }}'
          region: ap-south-1
          deployment_package: deploy.zip

**Comment by jaggaer-epastoor** [comment]
@Purushotham-grip , This issue has a solution. I have not verified it yet but someone confirmed it worked for them:
[https://github.com/einaregilsson/beanstalk-deploy/issues/110](https://github.com/einaregilsson/beanstalk-deploy/issues/110)

**Comment by reubinoff** [comment]
I think you need just to output the AWS credentials after assume Role:

```
    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v4
      id: creds
      with:
        role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
        aws-region: ${{ env.REGION }}
        role-session-name: DeploySession
        output-credentials: true

```
