### ISSUE TITLE
Create new environment for a PR

### ISSUE THREAD

**Issue by eshgovil** [einaregilsson/beanstalk-deploy#114]
I'd like to create a new EB deployment for a PR I just opened. I'm able to pull in the PR number for example to uniquely key this PR, but I cannot create new environments (same application):

```
      - name: Get pull request number
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "Pull request number is ${{ env.PR_NUMBER }}"

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: backend
          environment_name: backend-dev-${{ env.PR_NUMBER }}
          version_label: ${{ github.SHA }}
          region: us-west-1
          deployment_package: deploy.zip
```

Leads to

`Error: Deployment failed: Error: Status: 400. Code: InvalidParameterValue, Message: No Environment found for EnvironmentName = 'backend-dev-82'.`

In pipeline.

Is this possible to support, or even do unless you specify a configuration and environment variables etc?
