### ISSUE TITLE
Cannot read properties of undefined (reading 'VersionLabel')

### ISSUE THREAD

**Issue by SummySumanth** [einaregilsson/beanstalk-deploy#115]
I keep getting the error `Error: Deployment failed: TypeError: Cannot read properties of undefined (reading 'VersionLabel')` and I have checked that `github.sha` is available, but still this is failing .

below is my workflow
```
      - name: 🚀 Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v19
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: 'ap-south-1'
          application_name: 'summy.dev-backend'
          environment_name: 'Summydev-backend-env'
          version_label: ${{ github.sha }}
          version_description: 'Deploying from GitHub Actions'
          deployment_package: 'deployment-package.zip'
```
