### ISSUE TITLE
Trim input whitespaces before perform a deployment

### ISSUE THREAD

**Issue by pmlo-sirisak-l** [einaregilsson/beanstalk-deploy#12]
```
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
```

![Screen Shot 2020-03-12 at 13 24 03](https://user-images.githubusercontent.com/59025182/76493896-4bd65180-6466-11ea-967f-40f7b6490ccb.png)

Same happens with v6

**Comment by einaregilsson** [comment]
That's weird, doesn't look like any special characters are being used. As far as I know - is not considered a special character. Can you try it with a simple version label, e.g. abc and see if that works? Just wondering whether it's the version or something else causing the problem.

**Comment by pmlo-sirisak-l** [comment]
Here's are various variations I tried...
![Screen Shot 2020-03-12 at 18 16 43](https://user-images.githubusercontent.com/59025182/76518131-2579db80-6491-11ea-8a4f-69c881fd3548.png)
![Screen Shot 2020-03-12 at 18 28 37](https://user-images.githubusercontent.com/59025182/76518137-290d6280-6491-11ea-9607-325379906da1.png)
![Screen Shot 2020-03-12 at 18 41 39](https://user-images.githubusercontent.com/59025182/76518138-2ad72600-6491-11ea-8086-7a332c10abb9.png)

**Comment by einaregilsson** [comment]
Any chance that some kind of whitespace is messing things up? Tabs instead of spaces, trailing whitespace, anything like that?

**Comment by pmlo-sirisak-l** [comment]
Nope, though I used a string format, take a look...

![1A1C1EA7-1DE6-4178-B924-57868EC8B25C](https://user-images.githubusercontent.com/59025182/76585033-e76fcc80-650f-11ea-8c80-09dac186036f.png)

**Comment by einaregilsson** [comment]
Ok. Can you paste in here, in a code block the actual text from your deployment script, with hardcoded values, not ${{ ... }}} (except the access and secret keys of course), not using string formatting? Then I'll see if I can reproduce this here, copying the exact text.

**Comment by pmlo-sirisak-l** [comment]
You mean this?
```
      - name: Deploy to Target Environment
        uses: einaregilsson/beanstalk-deploy@v7
        with:
          aws_access_key: <<AWS_ACCESS_KEY_ID>>
          aws_secret_key: <<AWS_SECRET_ACCESS_KEY>>
          region: ap-southeast-1
          application_name: API
          environment_name: Docker-Staging-Fashion-API
          version_label: BasicExample
          deployment_package: deploy.zip
```
