### ISSUE TITLE
Error: Status 307, Message:

### ISSUE THREAD

**Issue by EclesioMeloJunior** [einaregilsson/beanstalk-deploy#17]
When I try to deploy my nodejs application to ELB I'm getting this error but i cannot recognize what's my mistake.

![image](https://user-images.githubusercontent.com/17255488/79081399-0322ea00-7ceb-11ea-8b08-8b00b0d18f04.png)

My **yml** file
```yml
name: CD Testing ELB

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1

      - name: Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: npm install --production

      - name: Generate Deployment Pacakge
        run: zip -r deploy.zip * -x "**node_modules"

      - name: Get Timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: "-"
          flags: "g"

      - name: Deploy on Beanstalk
        uses: einaregilsson/beanstalk-deploy@v9
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
          application_name: carrinho-digital-web-api
          environment_name: CarrinhoDigitalWebApi-env
          region: us-east-2
          version_label: "carrinho-digital-web-api-${{ steps.format-time.outputs.replaced }}"
          deployment_package: deploy.zip
          use_existing_version_if_available: true

```
