### ISSUE TITLE
If i want to deploy using docker with this action what should i make changes in here,Is this action will support docker?

### ISSUE THREAD

**Issue by adityaSharma369** [einaregilsson/beanstalk-deploy#18]
name: Your app name

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
#
    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installing NPM
      run: npm install

#     - name: Building application
#       run: npm run build

    - name: Generate deployment package
      run: zip -r deploy.zip * -x "**node_modules**"

    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time

    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'
    - name: docker build
      run: sudo docker build -f Dockerfile .
    - name: Beanstalk Deploy for app
      uses: einaregilsson/beanstalk-deploy@v9
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
        aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
        application_name: node-js-for-ebs
        environment_name: node-js-for-ebs-dev
        region: us-west-2
        version_label: "my-app-${{ steps.format-time.outputs.replaced }}"
        deployment_package: deploy.zip

    - name: Deployed!
      run: echo App deployed to ELB

**Comment by einaregilsson** [comment]
This action just deploys a zip file that EB accepts. If you put a dockerfile in there in the right way it should work, but we don't do anything special to support that. In your file above you're doing your docker build after creating your deployment package. Isn't it enough to just put a Dockerfile in your zip?

**Comment by adityaSharma369** [comment]
@einaregilsson ,yes DockerFile  is enough but i thought that we need to build docker file then i have to zip it.but later i came to know that dockerfile is enough and thank you for ur info

**Comment by JackMcKew** [comment]
Hi @adityaSharma369,

I'm currently trying to solve the same problem. Curious to know what the workflow you got working in the end was? From my understanding, I have zipped the Dockerfile intended for upload onto ElasticBeanstalk but it seems to fail on the deploy step:

<img width="733" alt="firefox_4yw8Aunwaf" src="https://user-images.githubusercontent.com/19178331/89244546-1d8e2400-d64a-11ea-9fcb-b1cbfdc0364f.png">

My current workflow is:

``` yaml
name: Test & Deploy
on: push

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Build Dev Docker Image
        run: docker build -t jackmckew/docker-react-dev -f Dockerfile.dev .

      - name: Run Test Suite
        run: docker run -e CI=true jackmckew/docker-react-dev npm run test -- --coverage

      # Zip Dockerfile for upload
      - name: Generate deployment package
        run: zip -r deploy.zip Dockerfile

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: "-"
          flags: "g"

      # Deploy to AWS
      - name: Deploy to AWS ElasticBeanstalk
        if: success()
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react
          environment_name: DockerReact-env
          region: us-east-2
          version_label: "docker-react-${{ steps.format-time.outputs.replaced }}"
          deployment_package: deploy.zip
```
