### ISSUE TITLE
Deploying to beanstalk error: command hooks failed

### ISSUE THREAD

**Issue by charlenecoffman** [einaregilsson/beanstalk-deploy#3]
I am seeing this error in the Elastic Beanstalk logs:

> 2019-11-17 21:27:22,941 [ERROR] Command hooks (HooksExecutor.exe appdeploy\enact) failed
2019-11-17 21:27:22,941 [ERROR] Error encountered during build of Hook-EnactAppDeploy: Command hooks failed
Traceback (most recent call last):
  File "cfnbootstrap\construction.pyc", line 544, in run_config
  File "cfnbootstrap\construction.pyc", line 138, in run_commands
  File "cfnbootstrap\command_tool.pyc", line 117, in apply
ToolError: Command hooks failed
2019-11-17 21:27:22,941 [ERROR] -----------------------BUILD FAILED!------------------------
2019-11-17 21:27:22,941 [ERROR] Unhandled exception during build: Command hooks failed
Traceback (most recent call last):
  File "cfn-init", line 171, in <module>
  File "cfnbootstrap\construction.pyc", line 129, in build
  File "cfnbootstrap\construction.pyc", line 530, in build
  File "cfnbootstrap\construction.pyc", line 544, in run_config
  File "cfnbootstrap\construction.pyc", line 138, in run_commands
  File "cfnbootstrap\command_tool.pyc", line 117, in apply
ToolError: Command hooks failed
>
I am honestly lost as to why it is not working for me. Here is the deploy job in my yml:
```
   - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v3
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        application_name: BudgeIt
        environment_name: dev-budgeit
        version_label: 11202013717
        region: us-east-1
        deployment_package: deployment.zip
```
