### ISSUE TITLE
Deployment failed: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by dakshshah96** [einaregilsson/beanstalk-deploy#31]
Running this GitHub action always throws an error for me saying that my deployment package does not exist:

![Screenshot 2020-07-16 16 31 06](https://user-images.githubusercontent.com/7896438/87663639-c51de200-c781-11ea-81be-63068918c3c0.png)

I've confirmed that the file exists using `ls -l` right before running the deployment step:

![Screenshot 2020-07-16 16 32 15](https://user-images.githubusercontent.com/7896438/87663726-eaaaeb80-c781-11ea-9a1c-4c93d1818ba2.png)

My workflow file looks like this:

```yml
name: Test & Deploy Packages
on:
  push:
    branches: [master]

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      apiServer: ${{ steps.filter.outputs.apiServer }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Check for changes
      uses: dorny/paths-filter@v2.2.0
      id: filter
      with:
        filters: '.github/filters.yml'

  api_server:
    runs-on: ubuntu-latest
    needs: changes
    defaults:
      run:
        working-directory: packages/api-server

    if: ${{ needs.changes.outputs.apiServer == 'true' }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"

    - name: Install dependencies
      run: yarn

    - name: Tests
      run: yarn test

    - name: Generate deployment package
      run: zip -r api-server-deploy.zip . -x "node_modules/*"

    - name: List files
      run: ls -l

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v10
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: tilt-api-server
        environment_name: alpha
        version_label: 12345
        region: ap-south-1
        deployment_package: api-server-deploy.zip

```

I'm unable to determine the cause for this. Would be great if someone can take a look at it to see if this is a bug with this GitHub action! Thanks.
