### ISSUE TITLE
Get AWS EB Env after deploying

### ISSUE THREAD

**Issue by Amraneze** [einaregilsson/beanstalk-deploy#32]
Can we get the env of the env that we deployed the file ? or use an argument to get the env something like this:
```
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: MyApplicationName
        environment_name: MyApplication-Environment
        version_label: 12345
        region: us-west-2
        deployment_package: deploy.zip
        deployment_env: true
```
The purpose is to get the CNAM from the Env and do an integration test based on it.

Thank you.
