### ISSUE TITLE
Fails to deploy printing usage, when all values provided

### ISSUE THREAD

**Issue by sveinungkb** [einaregilsson/beanstalk-deploy#38]
Not sure why this started failing. Does it not use the `aws_access_key` although provided perhaps?

```
Run einaregilsson/beanstalk-deploy@v10
  with:
    aws_access_key: ***
    aws_secret_key: ***
    application_name: myservice
    environment_name: myservice-env
    version_label: ef404dbe438457836316cd4ebe53b2b6afe99874
    region: us-east-1
    deployment_package: build/distributions/my-service.zip
    wait_for_deployment: false
  env:
    JAVA_HOME_8.0.265_x64: /opt/hostedtoolcache/jdk/8.0.265/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.265/x64
    JAVA_HOME_8_0_265_X64: /opt/hostedtoolcache/jdk/8.0.265/x64

beanstalk-deploy: Deploy a zip file to AWS Elastic Beanstalk
https://github.com/einaregilsson/beanstalk-deploy

Usage: beanstalk-deploy.js <application> <environment> <versionLabel> <region> [<filename>]

Environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY must be defined for the program to work.
If <filename> is skipped the script will attempt to deploy an existing version named <versionLabel>.
```
