### ISSUE TITLE
IS_GITHUB_ACTION not being set in GitHub Actions

### ISSUE THREAD

**Issue by JackMcKew** [einaregilsson/beanstalk-deploy#40]
Hi!

This action seems like a great idea! I'm trying to set up my workflow to upload my web application as a zip through GitHub Actions: https://github.com/JackMcKew/docker-react. Please find my relevant Github action logs at: https://github.com/JackMcKew/docker-react/actions.

Although, I've spent hours and no matter the combination of inputs, the action always errors out on https://github.com/einaregilsson/beanstalk-deploy/blob/master/beanstalk-deploy.js#L261 and prints accordingly. From further tracing, this conditional only runs if IS_GITHUB_ACTION is false, which is set by: https://github.com/einaregilsson/beanstalk-deploy/blob/master/beanstalk-deploy.js#L7.

I'm unsure as to why it isn't detecting that it is running as a GitHub action.

**Comment by JackMcKew** [comment]
A workaround to this problem is to use the npm package `beanstalk-deploy` under a run command in an action. This seems to work.

Example:

``` yaml
name: Test & Deploy
on: push

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Build Dev Docker Image
        run: docker build -t jackmckew/docker-react-dev -f Dockerfile.dev .

      - name: Run Test Suite
        run: docker run -e CI=true jackmckew/docker-react-dev npm run test -- --coverage

      # Zip Dockerfile for upload
      - name: Generate Deployment Package
        run: zip -r deploy.zip * -x "**node_modules**"

      - name: Get Timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run String Replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: "-"
          flags: "g"

      # Deploy to AWS
      - name: Install Dependencies & Deploy to AWS
        run: |
          sudo npm install -g beanstalk-deploy --unsafe-perm
          sudo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID}} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY}} beanstalk-deploy "docker-react" "DockerReact-env-1" "docker-react-${{ steps.format-time.outputs.replaced }}" "us-east-2" deploy.zip
      # # Deploy to AWS
      # This doesn't work, complains not enough arguments and IS_GITHUB_ACTION evaluates to false
      # - name: Deploy to AWS ElasticBeanstalk
      #   uses: einaregilsson/beanstalk-deploy@v10
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     application_name: "docker-react"
      #     environment_name: "DockerReact-env"
      #     version_label: "docker-react-${{ steps.format-time.outputs.replaced }}"
      #     region: "us-east-2"
      #     deployment_package: deploy.zip
      #     version_description: ${{github.SHA}}

```

With successful action logs: https://github.com/JackMcKew/docker-react/runs/943201859?check_suite_focus=true
