### ISSUE TITLE
Beanstalk application unresponsive after deploy a spring boot app  (zipped jar)

### ISSUE THREAD

**Issue by mrczpt** [einaregilsson/beanstalk-deploy#57]
Basically, after zipping the jar the zip file is sent to deploy to BE, this was working at some point but now after the deploy starts and the command giving a successful response the environment starts and then is on an unresponsive state, not even the bad gateway error.

I already check all the logs from BE and I could not find a root cause any ideas?

Here are the steps I been using
```
    - name: Generate deployment package
      run: zip  -j app-0.0.1-SNAPSHOT.jar.zip app-0.0.1-SNAPSHOT.jar

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: app
        environment_name: dev-api
        region: us-east-1
        version_label: ${{ steps.vars.outputs.sha_short }}
        deployment_package: app-0.0.1-SNAPSHOT.jar
```
