### ISSUE TITLE
Deployment failed: Error: Status: 400. Code: InvalidParameterValue, Message: No Application Version named '886765199' found.

### ISSUE THREAD

**Issue by stephanoparaskeva** [einaregilsson/beanstalk-deploy#58]
Everything I try results in an error, it seems impossible to use. 
This is my config:
```yml
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r deploy.zip docker-compose.yml Dockerrun.aws.json

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: archimedes
          environment_name: dev-archimedes
          region: eu-west-1
          version_label: ${{github.run_id}}
          version_description: none
          deployment_package: deploy.zip
```

**Comment by einaregilsson** [comment]
Hmm, the first one should work, although I would probably use `${{github.run_number}}` rather than `.run_id`. Try it with run_number and see if it works. And you can always look at Elastic Beanstalk and see exactly which application versions have already been created.

**Comment by akakakakakaa** [comment]
I faced same problem.

When I upload my source code test.zip to beanstalk, In bucket, key looks like /2021179bhG-test.zip instead of /{application_name}/test.zip.

**Comment by tetz2442** [comment]
@stephanoparaskeva double check that your **application_name** name is correct. I just created a new one and didn't realize the application name changed. I was getting the same error, because it was publishing my application versions to the wrong one.

**Comment by jclaessens97** [comment]
I have the same behaviour as the 3rd one with following config:

```yaml
deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r -j deploy.zip ./dev/* -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: dev
          environment_name: dev-env
          version_label: ${{ github.run_number }}
          existing_bucket_name: elasticbeanstalk-eu-west-1-xxxxxxxx
          region: eu-west-1
          deployment_package: deploy.zip
          use_existing_version_if_available: true
```

I first created a EBS environment, which already created a bucket for me so I used that bucket for the deploys.

It deploys succesfully, health is OK on EBS, but the pipeline fails with `ERROR: Error: Deployment failed: TypeError: Cannot read property 'VersionLabel' of undefined`

Anyone see what I'm missing here?
