### ISSUE TITLE
use_existing_version_if_available not detecting existing version

### ISSUE THREAD

**Issue by dnorth98** [einaregilsson/beanstalk-deploy#59]
Config

```yaml
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          application_name: 'Cloud Backup'
          environment_name: st-tb-cb-webapp-v3
          version_label: rewind-app-${{github.SHA}}
          version_description: Commit ${{github.SHA}} deployed by github actions
          region: us-east-1
          deployment_package: deploy.zip
          use_existing_version_if_available: true
          wait_for_deployment: true
          wait_for_environment_recovery: 60
```

When running 2 deploys from the same job, i'm getting

`Deployment failed: Error: Version rewind-app-07b8f5987797bb85fc36d8219679bb081cda158b already exists in S3!`

I thought this was due to a previous failure but to test this I just put 2 deploys one after the other one.  The first one works, but the second fails with the S3 error.

![image](https://user-images.githubusercontent.com/6616703/120213236-f61fcd80-c200-11eb-812d-823eb93aef8e.png)

I'm wondering if it has something to do with the space in the EB Application name OR that the app name is prepended to the source?  This is what shows for app versions - I can see that `07b8f5987797bb85fc36d8219679bb081cda158b` is clearly there.

![image](https://user-images.githubusercontent.com/6616703/120213398-25ced580-c201-11eb-9798-66640b7e1d95.png)
