### ISSUE TITLE
Use of `aws_session_token`

### ISSUE THREAD

**Issue by giraz82** [einaregilsson/beanstalk-deploy#65]
I'm trying to use a temporary access token with:

```yml
  uses: einaregilsson/beanstalk-deploy@v17
  with:
      aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_session_token: ${{ github.event.inputs.session_token }}
```
But I get:
```
Error: Deployment failed: Error: Status: 403. Code: InvalidClientTokenId, Message: The security token included in the request is invalid.
```

I also printed out `${{ github.event.inputs.session_token }}` just to be sure the string is correctly managed by GitHub runner.
With eb cli I can access of course.

Any idea?
Thank you.
