### ISSUE TITLE
How to set  option_settings?

### ISSUE THREAD

**Issue by ablegao** [einaregilsson/beanstalk-deploy#85]
This config in  .elasticbeanstalk/config.yml 

option_settings:
  aws:elasticbeanstalk:application:environment:
    FILE_SYSTEM_ID: xxxxxx
    MOUNT_DIRECTORY: '/efs'

how to set this?

**Comment by quiquelhappy** [comment]
I also need this

**Comment by dantehemerson** [comment]
You need to include/creaate the folder `.ebextensions` in your zip file and create a config file.

For instance:

file: `.ebextensions/options.config`
```
option_settings:
  aws:elasticbeanstalk:application:environment:
    FILE_SYSTEM_ID: xxxxxx
    MOUNT_DIRECTORY: '/efs'
```
