### ISSUE TITLE
dynamic version_label is not working

### ISSUE THREAD

**Issue by JoaoPedroCJ** [einaregilsson/beanstalk-deploy#97]
my pipeline works and sends the file to beanstalk but the running version name is not correct

![running](https://user-images.githubusercontent.com/32676353/217568495-cef461a9-45ef-4321-b4cb-e5975eaf9d33.png)

```yml
name: Deploy Node app on AWS Elastic Beanstalk

on:
  release:
    types: [prereleased]

env:
  EB_APP_NAME: application-api
  EB_ENV_NAME: application-env
  EB_VERSION_LABEL: a-pm-${GITHUB_RUN_NUMBER}

jobs:
  deploy_on_eb:
    runs-on: ubuntu-latest
    steps:
      - run: echo $EB_VERSION_LABEL
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - name: Create .zip file
        run: zip -r deploy.zip . -x '*.git*'
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ${{ env.EB_APP_NAME }}
          environment_name: ${{ env.EB_ENV_NAME }}
          version_label: ${{ env.EB_VERSION_LABEL }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
```
